server:
  port: 8080
spring:
  datasource:
    username: app_employees
    url: jdbc:mysql://localhost:3306/user?createDatabaseIfNotExist=true&serverTimezone=UTC
    password: app_employees
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082
          # jwk-set-uri: http://localhost:8082/oauth2/jwks