server:
  port: 8081
security:
  jwt:
    token:
      secret-key: 53ccr37
      expiration-time: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth_bd
    initialize: true
    username: app_employees
    password: app_employees
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      show-sql: true
