server:
  port: 8081
security:
  jwt:
    token:
      secret-key: 53ccr37
      expiration-time: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth_bd
    initialize: true
    username: app_employees
    password: app_employees
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      show-sql: true
  session:
    store-type: jdbc

api:
  auth:
    provider-uri: "http://localhost:8082"
    jks:
      keypass: 123456
      storepass: 123456
      alias: apiblog
      path: keystore/apiblog.jks