server:
  port: ${PORT:8081}

spring:
  application:
    name: blog-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mywebsite
    username: app_employees
    password: app_employees
    initialize: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.sendGrid.net
    port: 587
    username: apikey
    password:

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082
      client:
        registration:
          apiuser-client:
            provider: authblog
            client-id: apiuser
            client-secret: 123456
            authorization-grant-type: client_credentials
            scope: users:read
            client-name: apiuser-client
        provider:
          authblog:
            issuer-uri: http://localhost:8082
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
      instance:
        prefer-ip-address: true
        hostname: localhost

api:
  user-api:
    url: 'http://localhost:8083'
    encoded-credentials: 'YWRtaW5AZW1haWwuY29tOmFkbWlu'


blog:
  email:
    impl: smtp
    from: Ricardo Rodrigues Ferreira <noreply@email.com>